use trailerflix;
INSERT INTO Generos (id_genero, nombre_genero) VALUES (1, 'Música');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (2, 'Familia');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (3, 'Romance');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (4, 'Drama');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (5, 'Sci-Fi');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (6, 'Sucesos');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (7, 'Crimen');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (8, 'Tecnología');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (9, 'Suceso Real');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (10, 'Acción');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (11, 'Ficción');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (12, 'Terror');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (13, '¿Ficción?');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (14, 'Ciencia Ficción');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (15, 'Suspenso');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (16, 'Fantasía');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (17, 'Aventura');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (18, 'Comedia');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (19, 'Historia');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (20, 'Ciencia ficción');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (21, 'Intriga');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (22, 'Musical');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (23, 'Misterio');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (24, 'Animación');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (25, 'Western');
INSERT INTO Generos (id_genero, nombre_genero) VALUES (26, 'Futurista');